GET http://localhost:3003/api/blogs
###
POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Inl1a3Rlc3dhciIsImlkIjoiNjUwMmY0OGJlN2FiODQxYzE5ZGRiY2IwIiwiaWF0IjoxNjk1MTI0MjA1fQ.PaZKirNrS_TqD87uFEIKr2NWbUFueL0DH0Xfsf0y1kg

{
    "title": "Wa rum Wa rum",
    "author": "Sri Yukteswar",
    "url": "www.yogananda.org",
    "likes": 9
}
###
GET http://localhost:3003/api/blogs/64e356388b4314d21ef75391
###
DELETE http://localhost:3003/api/blogs/650424261f5d54184be1db13
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Inl1a3Rlc3dhciIsImlkIjoiNjUwMmY0OGJlN2FiODQxYzE5ZGRiY2IwIiwiaWF0IjoxNjk1MTk3NTc5fQ.40BwjJA9uvp_uxtwJV_FXF0mKsl9qbGtoXEb3HTbPAU
###
PUT http://localhost:3003/api/blogs/64e47bf9acf63ce52d5d1364
content-type: application/json

{
    "title": "Holy Science - The Source",
    "author": "Mahavtar Babaji",
    "url": "www.yogananda.org",
    "likes": 999
}
###
