GET http://localhost:3003/api/blogs
###
POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Inl1a3Rlc3dhciIsImlkIjoiNjUwMmY0OGJlN2FiODQxYzE5ZGRiY2IwIiwiaWF0IjoxNjk1MTk3NTc5fQ.40BwjJA9uvp_uxtwJV_FXF0mKsl9qbGtoXEb3HTbPAU

{
    "title": "Deutsch is einfach!",
    "author": "Daanish",
    "url": "www.yogananda.org",
    "likes": 1
}
###
GET http://localhost:3003/api/blogs/64e356388b4314d21ef75391
###
DELETE http://localhost:3003/api/blogs/650425faf26d757308d3ed08
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Inl1a3Rlc3dhciIsImlkIjoiNjUwMmY0OGJlN2FiODQxYzE5ZGRiY2IwIiwiaWF0IjoxNjk1MTk3NTc5fQ.40BwjJA9uvp_uxtwJV_FXF0mKsl9qbGtoXEb3HTbPAU
###
PUT http://localhost:3003/api/blogs/64e47bf9acf63ce52d5d1364
content-type: application/json

{
    "title": "Holy Science - The Source",
    "author": "Mahavtar Babaji",
    "url": "www.yogananda.org",
    "likes": 999
}
###
